version: "3"
services:
  backend:
    container_name: librus-csi
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      TZ: "Europen/Warsaw"
